### ISSUE TITLE
Fix dependency security vulnerability

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/oidc-auth-manager#23]
oidc-auth-manager transitively depends on `"base64url": "^2.0.0"` through a couple of old package versions of other libraries.

base64url should be updated to 3.0.0 in all dependencies because of https://nodesecurity.io/advisories/658

**Comment by dmitrizagidulin** [comment]
👍 , workin' on it.

**Comment by dmitrizagidulin** [comment]
Addressed by #24, closing.
