### ISSUE TITLE
seemingly uses two ASN.1 parsers

### ISSUE THREAD

**Issue by jonassmedegaard** [solid/oidc-auth-manager#38]
This module directly uses `asn1.js` indirectly via `@trust/jose` <- `@trust/webcrypto` and via `pem-jwk`, and also uses `asn1` indirectly via  `@trust/jose` <- `@trust/webcrypto` <- `node-rsa` <- `node-rsa` and `http-signature` <- `sshpk`<- `request` <- `jsonld` <- `rdflib`.

If correctly guessed (from just looking at the module names!) that those provide same/similar functionality, then it seems worthwhile to refactor to get rid of one of them.

See also <https://github.com/anvilresearch/webcrypto/issues/85>

**Comment by dmitrizagidulin** [comment]
`pem-jwk` has been removed, closing this issue.
