### ISSUE TITLE
Will this enable register via OIDC?

### ISSUE THREAD

**Issue by linonetwo** [solid/oidc-auth-manager#42]
In the solid login widget, there is no such an option to register WebID via OIDC.

**Comment by jaxoncreed** [comment]
Could you elaborate? You're able to register for an account and as a part of that, you either create a username which can become your webId, or opt to use an external webId.

**Comment by linonetwo** [comment]
I want to register through the following steps:

1. OIDC login through WechatSDK of some LoginAsAService, that LoginAAS provide a QRCode, user scan that QRCode to **create a LoginAAS account from WeChat account**
2. get OIDC token from LoginAAS in my server
3. create SoLiD POD use that OIDC token, in other words, **create a SoLiD account from LoginAAS account**
4. after creation, I get a cookie or session token from SoLiD auth client
5. return the cookie to the frontend, so the frontend can view content in his private POD

The result is, Use third-party LoginAAS to achieve "scan QRCode and get a SoLiD Pod".

**Comment by linonetwo** [comment]
I'm confused because I only find `solid start --auth oidc` in the doc, but it didn't said how to create account after server started.

**Comment by jaxoncreed** [comment]
Ah, I see. The built-in oidc code for node-solid-server does not allow you to implement a custom login system (including 3rd party integrations). It does follow the oidc spec but only for its own login system.

Having said that, we will be providing support for custom login systems in what is known as the [v-next server](https://github.com/inrupt/pod-server). It is not yet complete but we think we'll have the feature you need by the end of July.

**Comment by linonetwo** [comment]
Cool, a brand new implementation, watching your release. I will continue my trial after that.
