### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by philipbeadle** [solid/oidc-auth-manager#6]
Hi Dimitri,
I've just discovered Solid and followed the trail here.  I've been looking into Ethereum, Akasha, ceptr, IPFS.io and a bunch of other distributed technologies and found Solid.  After figuring out that the databox.me WebID uses the certificate method that now doesn't work due to changes in the browsers I found OIDC and I'd really like to help out.

Cheers
Phil

**Comment by dmitrizagidulin** [comment]
@philipbeadle thanks for reaching out! 
One thing that would be helpful is - try out the OIDC stack (write a small Solid application with it), and let us know if there are any questions or problems.

* You can find a [`solid-client`](https://github.com/solid/solid-client) OIDC build over at https://github.com/solid/releases
* Instructions for auth-related functions are available in the readme of https://github.com/solid/solid-auth-oidc
* Use https://solidtest.space as a server, or you can install the [`dz_oidc`](https://github.com/solid/node-solid-server/tree/dz_oidc) branch of solid-server (don't forget to run the `init` cli command)

**Comment by dmitrizagidulin** [comment]
@philipbeadle Also, there's a sample OIDC Auth app at https://github.com/solid/solid-auth-oidc/blob/master/demo/index.html

You can either run it directly at github.io at https://solid.github.io/solid-auth-oidc/demo/

or npm install `http-server`, check out a copy of the `solid-auth-oidc` repo, and `http-server demo/`.

**Comment by philipbeadle** [comment]
Ok, got some of this working.  Ive got the solid server running on localhost:8443 and the sample app on 8080.
When I enter my localhost address I get this
'''
solid-client.min.js:80 Getting provider from default popup UI
(index):90 onLoginSuccess() callback! webId:  undefined
solid-client.min.js:80 Auth client received event:  MessageEvent {isTrusted: true, data: Object, origin: "http://127.0.0.1:8080", lastEventId: "", source: Window…}
solid-client.min.js:80 Provider selected:  https://localhost:8443/
solid-client.min.js:80 Registering public client...
solid-client.min.js:80 GET https://localhost:8443//.well-known/openid-configuration 401 (Unauthorized)
value @ solid-client.min.js:80
(anonymous) @ solid-client.min.js:80
solid-client.min.js:80 Error in rp.discover() while fetching provider config
(anonymous) @ solid-client.min.js:80
solid-client.min.js:80 Error in RelyingParty.register(): SyntaxError: Unexpected token A in JSON at position 0
(anonymous) @ solid-client.min.js:80
solid-client.min.js:80 Uncaught (in promise) TypeError: Cannot read property 'serialize' of undefined
    at e.value (solid-client.min.js:80)
    at solid-client.min.js:80
'''
The local app logs in with my solidtest.space webid

I'm using the dz_oidc branch too.  Any clues as to what's going wrong here?

**Comment by dmitrizagidulin** [comment]
@philipbeadle thanks! Looking into it. (ping me on Gitter when you have a chance, I have some questions)

**Comment by dmitrizagidulin** [comment]
@philipbeadle I suspect the issue might be - do you have `"auth": "oidc"` enabled in your configuration? A 401 Unauthorized as a response to `GET https://localhost:8443/.well-known/openid-configuration` suggests the server is running in webid-tls mode.

**Comment by dmitrizagidulin** [comment]
I opened an issue for this, https://github.com/solid/solid-auth-oidc/issues/5

**Comment by philipbeadle** [comment]
@dmitrizagidulin  Ive got this as my config

`
{
  "root": "/Users/philipbeadle/Projects/SoLiD",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": true,
  "mount": "/",
  "sslKey": "/Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem",
  "sslCert": "/Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem",
  "idp": false,
  "proxy": "/proxy",
  "auth": "oidc"
}
`
I added the `"auth": "oidc"` and restarted the server and now when I go to https://localhost:8443/ I get
Access to https://localhost:8443/ requires authorization (401), even if i now remove that line.  

I'm in Melbourne Aus UTC+10 lets organise a gitter chat soon.

**Comment by dmitrizagidulin** [comment]
Ok, that's closer. (the 401 Unauthorized response is expected when you access `/` when not logged in).
Have you gone through the `node bin/solid.js init` setup wizard? I'm not seeing the `configPath` and `dbPath` settings.

**Comment by philipbeadle** [comment]
Yep, just ran it again to make sure. There was no question about dbpath or config path.

**Comment by dmitrizagidulin** [comment]
@philipbeadle It looks like there's some confusion between a globally installed Solid server, and a locally installed one. Running `solid init` most likely hits the globally installed one (which is why you're not seeing the config db questions). If running the local init gives you that error, it looks like you may have forgot to run `npm install` locally.

**Comment by philipbeadle** [comment]
Ok, fixed that with npm install however there is no change.

Philips-MBP-2:node-solid-server philipbeadle$ node bin/solid.js init
? Path to the folder you want to serve. Default is /Users/philipbeadle/Projects/SoLiD/node-solid-server
? SSL port to run on. Default is 8443
? Solid server uri (with protocol, hostname and port) https://localhost:8443
? Enable WebID authentication Yes
? Serve Solid on URL path /
? Path to the SSL private key in PEM format /Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem
? Path to the SSL certificate key in PEM format /Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem
? Enable multi-user mode (users can sign up for accounts) No
? Do you want to have a CORS proxy endpoint? Yes
? Serve proxy on path /proxy
? Do you want to set up an email service? No
config created on /Users/philipbeadle/Projects/SoLiD/node-solid-server/config.json

Still creates the same config.


{
  "root": "/Users/philipbeadle/Projects/SoLiD/node-solid-server",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": true,
  "mount": "/",
  "sslKey": "/Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem",
  "sslCert": "/Users/philipbeadle/Projects/SoLiD/certificate/localhost.pem",
  "idp": false,
  "proxy": "/proxy"
}

**Comment by dmitrizagidulin** [comment]
So that still looks like an earlier version, judging by the config wizard. Can you do a `git fetch origin` / `git checkout dz_oidc` / `git rebase origin/dz_oidc`?

**Comment by philipbeadle** [comment]
Ok got the node server working with OIDC, but now theres no demo folder in this repo to try it out.  Is there another demo now?

**Comment by dmitrizagidulin** [comment]
The demo folder is in another repo, https://github.com/solid/solid-auth-oidc 
(The names are very similar -- this one is a server-side auth manager, and that one is the client-side).

**Comment by philipbeadle** [comment]
Ah thanx :)  Still trying to get my head around all this.  Although it may look like it, i'm not a noob :)  My main claim to fame is http://www.dnnplatform.com which I built with a bunch of others.  I'd really like to get solid.social up and running with the OIDC auth but cant figure out what the user object is supposed to look like that gets returned in the HEADERS in the current code.  Are you familiar with that project at all?

**Comment by dmitrizagidulin** [comment]
DNN looks pretty cool (and no, no worries, this branch definitely still needs more documentation/explanations)!

I'm not quite familiar with solid.social, I know it's Melvin's project and I've seen screenshots, but haven't looked at the code. If it's still using WebID-TLS auth, then I think you're referring to the `User:` header, yeah? That should just be a WebID URI string. Also, lets take the conversation to gitter, so as not to spam this thread.

**Comment by dmitrizagidulin** [comment]
Closing - let me know if you have any other questions.
